const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const PORT=Number(process.env.PORT||10000), ROOT=__dirname, INDEX=path.join(ROOT,'index.html');
const clients=new Set(), files=new Map();
const TTL=30*60*1000, MAX=100*1024*1024;
function id(){return crypto.randomBytes(16).toString('hex')}
function frame(op,p){p=Buffer.from(p||'');let h;if(p.length<126){h=Buffer.from([0x80|op,p.length])}else if(p.length<65536){h=Buffer.alloc(4);h[0]=0x80|op;h[1]=126;h.writeUInt16BE(p.length,2)}else{h=Buffer.alloc(10);h[0]=0x80|op;h[1]=127;h.writeUInt32BE(Math.floor(p.length/4294967296),2);h.writeUInt32BE(p.length>>>0,6)}return Buffer.concat([h,p])}
function send(c,o){if(!c.destroyed)try{c.write(frame(1,JSON.stringify(o)))}catch(e){}}
function broadcast(o){for(const c of [...clients])send(c,o)}
function remove(c){clients.delete(c);broadcast({type:'presence',online:clients.size})}
function parse(c){while(c.buf.length>=2){let a=c.buf[0],b=c.buf[1],fin=!!(a&128),op=a&15,masked=!!(b&128),n=b&127,off=2;if(!masked){c.destroy();return}if(n===126){if(c.buf.length<4)return;n=c.buf.readUInt16BE(2);off=4}else if(n===127){if(c.buf.length<10)return;let hi=c.buf.readUInt32BE(2);if(hi){c.destroy();return}n=c.buf.readUInt32BE(6);off=10}if(n>1024*1024){c.destroy();return}if(c.buf.length<off+4+n)return;let m=c.buf.subarray(off,off+4);off+=4;let p=c.buf.subarray(off,off+n);c.buf=c.buf.subarray(off+n);for(let i=0;i<p.length;i++)p[i]^=m[i%4];if(op===8){try{c.write(frame(8))}catch(e){}c.end();return}if(op===9){try{c.write(frame(10,p))}catch(e){}continue}if(op!==1){continue}let d;try{d=JSON.parse(p.toString())}catch(e){continue}handle(c,d);if(!fin)continue}}
function handle(c,d){if(!d||typeof d.type!=='string')return;if(d.type==='hello'){c.uid=String(d.userId||'').slice(0,100);c.name=String(d.name||'User').slice(0,40);send(c,{type:'ready',online:clients.size,time:Date.now()});broadcast({type:'presence',online:clients.size});return}if(d.type==='message'){broadcast({type:'message',messageId:String(d.messageId||id()),senderId:String(d.senderId||c.uid),senderName:String(d.senderName||c.name).slice(0,40),messageType:d.messageType==='file'?'file':'text',text:String(d.text||'').slice(0,4000),fileId:String(d.fileId||''),fileName:String(d.fileName||'').slice(0,120),mime:String(d.mime||'').slice(0,120),size:Number(d.size||0),timestamp:Date.now()})}}
function upgrade(req,s){let key=req.headers['sec-websocket-key'];if(!key){s.end();return}let accept=crypto.createHash('sha1').update(key+'258EAFA5-E914-47DA-95CA-C5AB0DC85B11').digest('base64');s.write('HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Accept: '+accept+'\r\n\r\n');s.setNoDelay(true);clients.add(s);s.buf=Buffer.alloc(0);send(s,{type:'connected',online:clients.size,time:Date.now()});s.on('data',x=>{s.buf=Buffer.concat([s.buf,x]);try{parse(s)}catch(e){s.destroy()}});s.on('close',()=>remove(s));s.on('error',()=>remove(s))}
function json(res,n,o){let b=Buffer.from(JSON.stringify(o));res.writeHead(n,{'Content-Type':'application/json','Content-Length':b.length,'Cache-Control':'no-store','Access-Control-Allow-Origin':'*'});res.end(b)}
const server=http.createServer((req,res)=>{let u=new URL(req.url,'http://localhost');if(req.method==='GET'&&(u.pathname==='/'||u.pathname==='/index.html'))return fs.readFile(INDEX,(e,b)=>e?res.end('index.html missing'):((res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-cache'}),res.end(b))));if(req.method==='GET'&&u.pathname==='/health')return json(res,200,{ok:true,online:clients.size});if(req.method==='POST'&&u.pathname==='/upload'){let fid=id(),name=String(u.searchParams.get('name')||'file.bin').replace(/[^a-zA-Z0-9._-]/g,'_').slice(0,120),mime=String(u.searchParams.get('mime')||'application/octet-stream').slice(0,120),fp=path.join(ROOT,'.wc_'+fid+'_'+name),out=fs.createWriteStream(fp),total=0,failed=false;req.on('data',x=>{if(failed)return;total+=x.length;if(total>MAX){failed=true;req.destroy();out.destroy();try{fs.unlinkSync(fp)}catch(e){};return}out.write(x)});req.on('end',()=>{if(failed)return json(res,413,{ok:false,error:'FILE_TOO_LARGE'});out.end(()=>{files.set(fid,{fp,name,mime,size:total,exp:Date.now()+TTL});json(res,200,{ok:true,fileId:fid,fileName:name,mime,size:total})})});req.on('error',()=>{failed=true;out.destroy();try{fs.unlinkSync(fp)}catch(e){}});return}if(req.method==='GET'&&u.pathname.startsWith('/file/')){let f=files.get(u.pathname.slice(6));if(!f||f.exp<Date.now()||!fs.existsSync(f.fp)){res.writeHead(404);return res.end('expired')}res.writeHead(200,{'Content-Type':f.mime,'Content-Length':f.size,'Cache-Control':'no-store'});return fs.createReadStream(f.fp).pipe(res)}res.writeHead(404);res.end('Not found')});
server.on('upgrade',(req,s)=>{let u=new URL(req.url,'http://localhost');if(u.pathname==='/ws')upgrade(req,s);else s.end('HTTP/1.1 404 Not Found\r\n\r\n')});
setInterval(()=>{for(const [k,f] of files){if(f.exp<Date.now()){try{fs.unlinkSync(f.fp)}catch(e){}files.delete(k)}}},60000);
server.listen(PORT,'0.0.0.0',()=>console.log('World Chat listening on '+PORT));
